spring:
  kafka:
    consumer:
      #bootstrap-servers: http://10.211.55.11:9092,http://10.211.55.12:9092
      # 配置消费者消息offset是否自动重置(消费者重连会能够接收最开始的消息)
      bootstrap-servers: http://192.168.8.128:9092
      auto-offset-reset: earliest
      enable-auto-commit: false
      # 发送的对象信息变为json格式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "com.product.pojo"
    producer:
      #bootstrap-servers: http://10.211.55.11:9092,http://10.211.55.19:9092,http://10.211.55.20:9092
      bootstrap-servers: http://192.168.8.128:9092
      # 发送的对象信息变为json格式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      ack-mode: manual_immediate
    #bootstrap-servers: http://192.168.8.128:9092,http://192.168.8.129:9092,http://192.168.8.130:9092
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

kafka:
  topic:
    my-topic: my-topic
    my-topic2: my-topic2


