fdfs:
  soTimeout: 6000
  connectTimeout: 6000
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    -  101.35.245.41:22122


server:
  port: 8088

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB